<?php
/**
 * Render: Testimonial Item Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Ambrygen\Theme\Core\Helper;

/**
 * Safely access attributes.
 *
 * @var array $attributes Block attributes.
 */
$ambrygen_attributes = ( isset( $attributes ) && is_array( $attributes ) ) ? $attributes : array();

/**
 * Retrieve attributes with defaults.
 */
$ambrygen_logo_id = ! empty( $ambrygen_attributes['logoId'] )
	? absint( $ambrygen_attributes['logoId'] )
	: 0;
$ambrygen_logo_url = ! empty( $ambrygen_attributes['logo'] )
	? esc_url_raw( $ambrygen_attributes['logo'] )
	: '';
$ambrygen_logo_alt = ! empty( $ambrygen_attributes['logoAlt'] )
	? sanitize_text_field( $ambrygen_attributes['logoAlt'] )
	: '';

$ambrygen_quote = ! empty( $ambrygen_attributes['quote'] )
	? $ambrygen_attributes['quote']
	: '';

$ambrygen_author = ! empty( $ambrygen_attributes['author'] )
	? $ambrygen_attributes['author']
	: '';

$ambrygen_role = ! empty( $ambrygen_attributes['role'] )
	? $ambrygen_attributes['role']
	: '';
$ambrygen_has_quote  = '' !== trim( wp_strip_all_tags( $ambrygen_quote ) );
$ambrygen_has_author = '' !== trim( wp_strip_all_tags( $ambrygen_author ) );
$ambrygen_has_role   = '' !== trim( wp_strip_all_tags( $ambrygen_role ) );

/**
 * Block context.
 */
$ambrygen_context = ( isset( $block ) && $block instanceof WP_Block )
	? $block->context
	: array();

$ambrygen_main_image_id = ! empty( $ambrygen_context['ambrygen/mainImageId'] )
	? absint( $ambrygen_context['ambrygen/mainImageId'] )
	: 0;

$ambrygen_main_image_url = ! empty( $ambrygen_context['ambrygen/mainImage'] )
	? esc_url_raw( $ambrygen_context['ambrygen/mainImage'] )
	: '';
$ambrygen_main_image_alt = ! empty( $ambrygen_context['ambrygen/mainImageAlt'] )
	? sanitize_text_field( $ambrygen_context['ambrygen/mainImageAlt'] )
	: '';

/**
 * Wrapper attributes.
 */
$ambrygen_wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'js-gsap-fade ambry-testimonials__grid__item swiper-slide',
	)
);
?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>

	<?php if ( $ambrygen_main_image_id || $ambrygen_main_image_url ) : ?>
	<div class="ambry-testimonials__grid__item__thumb" aria-hidden="true">
		<?php
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Helper returns escaped image markup from a sanitized attachment ID or URL.
		echo Helper::image_from_source(
			$ambrygen_main_image_id,
			$ambrygen_main_image_url,
			'medium_large',
			array(
				'loading'  => 'lazy',
				'decoding' => 'async',
				'alt'      => $ambrygen_main_image_alt,
			)
		);
		?>
	</div>
	<?php endif; ?>

	<div class="ambry-testimonials__grid__item__content">

		<?php if ( $ambrygen_logo_id || $ambrygen_logo_url ) : ?>
			<?php
			// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Helper returns escaped image markup from a sanitized attachment ID or URL.
			echo Helper::image_from_source(
				$ambrygen_logo_id,
				$ambrygen_logo_url,
				'medium_large',
				array(
					'class'    => 'ambry-testimonials__grid__logo',
					'loading'  => 'lazy',
					'decoding' => 'async',
					'alt'      => $ambrygen_logo_alt,
				)
			);
			?>
			<div class="is-style-gl-s32" aria-hidden="true"></div>
		<?php endif; ?>

		<?php if ( $ambrygen_has_quote ) : ?>
		<blockquote class="ambry-testimonials__grid__item__quote body2-reg">
			<p>
				<?php echo wp_kses_post( $ambrygen_quote ); ?>
			</p>
		</blockquote>
		<?php endif; ?>

		<?php if ( $ambrygen_has_author || $ambrygen_has_role ) : ?>
		<cite class="ambry-testimonials__layout__author-details">
			<?php if ( $ambrygen_has_author ) : ?>
			<div class="ambry-testimonials__layout__author-details__author body2-medium">
				<?php echo esc_html( $ambrygen_author ); ?>
			</div>
			<?php endif; ?>

			<?php if ( $ambrygen_has_role ) : ?>
				<div class="ambry-testimonials__layout__author-details__role body2-medium">
					<?php echo esc_html( $ambrygen_role ); ?>
				</div>
			<?php endif; ?>
		</cite>
		<?php endif; ?>
	</div>

</div>
