<?php
/**
 * Render: Careers Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Ambrygen\Theme\Core\Helper;

$ambrygen_attributes    = $attributes ?? array();
$ambrygen_block_id      = isset( $ambrygen_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_attributes['blockId'] ) : '';
$ambrygen_title         = isset( $ambrygen_attributes['title'] ) ? $ambrygen_attributes['title'] : '';
$ambrygen_intro         = isset( $ambrygen_attributes['intro'] ) ? $ambrygen_attributes['intro'] : '';
$ambrygen_heading_level = Helper::get_heading_tag( $ambrygen_attributes['headingLevel'] ?? 'h2', 'h2' );

$ambrygen_video_array = isset( $ambrygen_attributes['videoObj'] ) && is_array( $ambrygen_attributes['videoObj'] )
	? $ambrygen_attributes['videoObj']
	: array();
$ambrygen_video_url   = isset( $ambrygen_video_array['url'] ) ? esc_url_raw( $ambrygen_video_array['url'] ) : '';

$ambrygen_video_poster = isset( $ambrygen_attributes['videoPoster'] ) && is_array( $ambrygen_attributes['videoPoster'] )
	? $ambrygen_attributes['videoPoster']
	: array();

$ambrygen_video_type = isset( $ambrygen_attributes['videoType'] ) ? sanitize_key( $ambrygen_attributes['videoType'] ) : 'mp4'; // mp4 | embed.

$ambrygen_careers_link_top = isset( $ambrygen_attributes['link'] ) && is_array( $ambrygen_attributes['link'] )
	? $ambrygen_attributes['link']
	: array();

$ambrygen_careers_link_bottom = isset( $ambrygen_attributes['careerslink'] ) && is_array( $ambrygen_attributes['careerslink'] )
	? $ambrygen_attributes['careerslink']
	: array();

$ambrygen_video_poster_url = ! empty( $ambrygen_video_poster['url'] )
	? esc_url_raw( $ambrygen_video_poster['url'] )
	: '';

$ambrygen_wrapper_attributes         = get_block_wrapper_attributes(
	$ambrygen_block_id
		? array(
			'class' => 'careers-highlight',
			'id'    => $ambrygen_block_id,
		)
		: array(
			'class' => 'careers-highlight',
		)
);
$ambrygen_careers_link_bottom_target = ! empty( $ambrygen_careers_link_bottom['target'] )
	? esc_attr( $ambrygen_careers_link_bottom['target'] )
	: '_self';

$ambrygen_careers_link_top_target = ! empty( $ambrygen_careers_link_top['target'] )
	? esc_attr( $ambrygen_careers_link_top['target'] )
	: '_self';

$ambrygen_iframe_src = '';

if ( 'embed' === $ambrygen_video_type ) {
	$ambrygen_iframe_src = Helper::get_iframe_src( $ambrygen_attributes['videoUrl'] ?? '' );
}

$ambrygen_play_icon_src  = get_theme_file_uri( 'assets/src/images/play-icon.svg' );
$ambrygen_pause_icon_src = get_theme_file_uri( 'assets/src/images/pause-icon.svg' );

?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="careers-highlight__header block__rowflex">
		<<?php echo tag_escape( $ambrygen_heading_level ); ?> class="careers-highlight__title block__rowflex--heading-title heading-4 mb-0 js-gsap-fade">
			<?php echo wp_kses_post( $ambrygen_title ); ?>
		</<?php echo tag_escape( $ambrygen_heading_level ); ?>>

		<div class="careers-highlight__intro block__rowflex--block-content subtitle1-reg js-gsap-fade">
			<p><?php echo wp_kses_post( $ambrygen_intro ); ?></p>
			<?php if ( ! empty( $ambrygen_careers_link_top['text'] ) && ! empty( $ambrygen_careers_link_top['url'] ) ) : ?>
				<div class="block_rowflex-link">
							<a
								href="<?php echo esc_url( $ambrygen_careers_link_top['url'] ); ?>"
								class="site-btn is-style-site-text-btn has-right-arrow"
								target="<?php echo esc_attr( $ambrygen_careers_link_top_target ); ?>"
								<?php if ( '_blank' === $ambrygen_careers_link_top_target ) : ?>
									rel="noopener noreferrer"
								<?php endif; ?>
							>
						<?php echo esc_html( $ambrygen_careers_link_top['text'] ); ?>
					</a>
				</div>
			<?php endif; ?>
		</div>
	</div>

	<div class="is-style-gl-s50"></div>

	<div class="careers-highlight__row">
		<div class="careers-highlight__left">
			<div class="custom-scroll-jobs">
				<div class="careers-highlight__jobs">
					<?php echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- InnerBlocks content is rendered by WordPress. ?>
				</div>
			</div>

			<?php if ( ! empty( $ambrygen_careers_link_bottom['text'] ) && ! empty( $ambrygen_careers_link_bottom['url'] ) ) : ?>
				<div class="block-btn js-gsap-fade">
					<div class="is-style-gl-s32"></div>
					<a
						href="<?php echo esc_url( $ambrygen_careers_link_bottom['url'] ); ?>"
						class="site-btn is-style-site-text-btn has-right-arrow"
						target="<?php echo esc_attr( $ambrygen_careers_link_bottom_target ); ?>"
						<?php if ( '_blank' === $ambrygen_careers_link_bottom_target ) : ?>
							rel="noopener noreferrer"
						<?php endif; ?>
					>
						<?php echo esc_html( $ambrygen_careers_link_bottom['text'] ); ?>
					</a>
				</div>
			<?php endif; ?>
		</div>

		<div class="careers-highlight__right">
			<div class="careers-highlight__media media_video js-gsap-fade">
				<?php if ( 'mp4' === $ambrygen_video_type && $ambrygen_video_url ) : ?>
					<video class="videos" playsinline muted preload="metadata" loop
						<?php if ( $ambrygen_video_poster_url ) : ?>
							poster="<?php echo esc_url( $ambrygen_video_poster_url ); ?>"
						<?php endif; ?>
					>
						<source src="<?php echo esc_url( $ambrygen_video_url ); ?>" type="video/mp4">
					</video>
				<?php elseif ( 'embed' === $ambrygen_video_type ) : ?>
					<?php if ( $ambrygen_iframe_src ) : ?>
						<div class="careers-highlight__media video-embed media_video">
							<iframe
								src="<?php echo esc_url( $ambrygen_iframe_src ); ?>"
								title="<?php esc_attr_e( 'Video', 'ambrygen-web' ); ?>"
								frameborder="0"
								allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
								allowfullscreen
							></iframe>
						</div>
					<?php else : ?>
						<div class="videos-placeholder"><?php esc_html_e( 'Invalid video URL', 'ambrygen-web' ); ?></div>
					<?php endif; ?>
				<?php endif; ?>
				<div
					class="play-icon-video"
					role="button"
					tabindex="0"
					aria-label="<?php esc_attr_e( 'Open video', 'ambrygen-web' ); ?>"
				>
					<div class="play-icon circle-icon">
						<img src="<?php echo esc_url( $ambrygen_play_icon_src ); ?>" class="play-icon__img" alt="" aria-hidden="true">
					</div>
					<div class="pause-icon circle-icon">
						<img src="<?php echo esc_url( $ambrygen_pause_icon_src ); ?>" class="pause-icon__img" alt="" aria-hidden="true">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
