<?php
/**
 * Render: Theme Video Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

use Ambrygen\Theme\Core\Helper;

	// Block attributes.
	$theme_video_attributes       = $attributes ?? array();
	$theme_video_block_id         = $theme_video_attributes['blockId'] ?? '';
	$theme_video_link             = isset( $theme_video_attributes['link'] ) && is_array( $theme_video_attributes['link'] )
	? $theme_video_attributes['link']
	: array();
	$theme_video_heading          = $theme_video_attributes['heading'] ?? '';
	$theme_video_heading_tag      = $theme_video_attributes['headingTag'] ?? 'h2';
	$theme_video_description      = $theme_video_attributes['description'] ?? '';
	$theme_video_show_description = isset( $theme_video_attributes['showDescription'] ) ? (bool) $theme_video_attributes['showDescription'] : true;
	$theme_video_video_url        = $theme_video_attributes['videoUrl'] ?? '';
	$theme_video_video_type       = $theme_video_attributes['videoType'] ?? 'embed';
	$theme_video_iframe_url       = $theme_video_attributes['iframeUrl'] ?? '';
	$theme_video_image_url        = $theme_video_attributes['imageUrl'] ?? '';
	$theme_video_image_id         = absint( $theme_video_attributes['imageId'] ?? 0 );
	$theme_video_show_image       = ! empty( $theme_video_attributes['showImage'] );
	$theme_video_is_header_vertical = ! empty( $theme_video_attributes['isHeaderVertical'] );

	$theme_video_poster_image = isset( $theme_video_attributes['posterImage'] ) && is_array( $theme_video_attributes['posterImage'] )
	? $theme_video_attributes['posterImage']
	: array();

	$theme_video_poster_image_id = isset( $theme_video_poster_image['id'] )
	? (int) $theme_video_poster_image['id']
	: 0;

	$theme_video_poster_url = isset( $theme_video_poster_image['url'] )
	? esc_url( $theme_video_poster_image['url'] )
	: '';

	$theme_video_iframe_src = Helper::get_iframe_src( $theme_video_iframe_url );

	// Determine iframe source.

	// Extract URLs from image objects.
	$theme_video_wrapper_attributes = get_block_wrapper_attributes(
		$theme_video_block_id
		? array(
			'class' => 'features-media',
			'id'    => $theme_video_block_id,
		)
		: array(
			'class' => 'features-media',
		)
	);
	$theme_video_play_icon_src      = get_theme_file_uri( 'assets/src/images/play-icon.svg' );
	$theme_video_pause_icon_src     = get_theme_file_uri( 'assets/src/images/pause-icon.svg' );
	$theme_video_link_target        = ! empty( $theme_video_link['target'] )
	? esc_attr( $theme_video_link['target'] )
	: '_self';

	?>

<div <?php echo $theme_video_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="features-media__header block__rowflex is-<?php echo $theme_video_is_header_vertical ? 'vertical' : 'horizontal'; ?>">
		<<?php echo esc_html( $theme_video_heading_tag ); ?> class="block-title block__rowflex--heading-title heading-2 mb-0 js-gsap-fade">
				<?php
					echo wp_kses(
						$theme_video_heading,
						Helper::allowed_heading_html()
					);
					?>
		</<?php echo esc_html( $theme_video_heading_tag ); ?>>
		<?php if ( $theme_video_show_description && $theme_video_description ) : ?>
		<div class="block__rowflex--block-content subtitle1-reg js-gsap-fade">
			<p><?php echo wp_kses_post( $theme_video_description ); ?></p>
			<?php if ( ! empty( $theme_video_link ) && ! empty( $theme_video_link['text'] ) && ! empty( $theme_video_link['url'] ) ) : ?>
			<div class="block_rowflex-link js-gsap-fade">
				<a
					href="<?php echo esc_url( $theme_video_link['url'] ); ?>"
					class="site-btn is-style-site-text-btn has-right-arrow"
					target="<?php echo esc_attr( $theme_video_link_target ); ?>"
					<?php echo( '_blank' === $theme_video_link_target ) ? 'rel="noopener noreferrer"' : ''; ?>
				>
					<?php echo esc_html( $theme_video_link['text'] ); ?>
				</a>
			</div>
		<?php endif; ?>
		</div>
		<?php endif; ?>

	</div>

	<div class="is-style-gl-s50" aria-hidden="true"></div>

	<!-- <div class="features-media__video media_video"> -->
	<?php if ( $theme_video_show_image ) : ?>
		<div class="features-media has-image js-gsap-fade">
			<?php
				echo Helper::image_with_placeholder( // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
					$theme_video_image_id,
					'full',
					array(
						'class'   => 'features-media__image',
						'loading' => 'lazy',
					)
				);

			?>
		</div>
	<?php endif; ?>
	<?php if ( ! $theme_video_show_image && ( ( 'embed' === $theme_video_video_type && $theme_video_iframe_src ) || ( 'mp4' === $theme_video_video_type && $theme_video_video_url ) ) ) : ?>

	<div class="features-media__video media_video js-gsap-fade">
		<?php if ( ! $theme_video_show_image && 'embed' === $theme_video_video_type && $theme_video_iframe_src ) : ?>
			<div class="features-media__video-wrapper features-media__video-wrapper--iframe">
					<iframe
						src="<?php echo esc_url( $theme_video_iframe_src ); ?>"
						title="<?php esc_attr_e( 'Theme video', 'ambrygen' ); ?>"
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
						allowfullscreen
						class="features-media__iframe"
					></iframe>

					<div class="play-icon-video">
							<div class="play-icon circle-icon">
								<img src="<?php echo esc_url( $theme_video_play_icon_src ); ?>" class="play-icon__img" alt="Play Icon">
							</div>
							<div class="pause-icon circle-icon">
								<img src="<?php echo esc_url( $theme_video_pause_icon_src ); ?>" class="pause-icon__img" alt="Pause Icon">
							</div>
					</div>
			</div>
		<?php endif; ?>

		<?php if ( ! $theme_video_show_image && 'mp4' === $theme_video_video_type && $theme_video_video_url ) : ?>
			<div class="features-media__video-wrapper">
				<video
					class="videos"
					playsinline
					muted
					preload="metadata"
					loop
					poster="<?php echo esc_url( $theme_video_poster_url ); ?>"
					controls
				>
					<source src="<?php echo esc_url( $theme_video_video_url ); ?>" type="video/mp4">
					<?php esc_html_e( 'Your browser does not support the video tag.', 'ambrygen' ); ?>
				</video>

					<div class="play-icon-video">
							<div class="play-icon circle-icon">
								<img src="<?php echo esc_url( $theme_video_play_icon_src ); ?>" class="play-icon__img" alt="Play Icon">
							</div>
							<div class="pause-icon circle-icon">
								<img src="<?php echo esc_url( $theme_video_pause_icon_src ); ?>" class="pause-icon__img" alt="Pause Icon">
							</div>
					</div>
			</div>
		<?php endif; ?>
	</div>
	<?php endif; ?>
</div>
