<?php
/**
 * Render: Two Column Icon Grid Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

use Ambrygen\Theme\Core\Helper;

defined( 'ABSPATH' ) || exit;

$ambrygen_attributes  = is_array( $attributes ) ? $attributes : array();
$ambrygen_block_id    = isset( $ambrygen_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_attributes['blockId'] ) : '';
$ambrygen_anchor      = isset( $ambrygen_attributes['anchor'] ) ? sanitize_html_class( $ambrygen_attributes['anchor'] ) : '';
$ambrygen_block_id    = isset( $ambrygen_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_attributes['blockId'] ) : '';
$ambrygen_heading     = $ambrygen_attributes['heading'] ?? '';
$ambrygen_heading_tag = Helper::get_heading_tag(
	$ambrygen_attributes['headingTag'] ?? 'h2',
	'h2'
);
$ambrygen_description = $ambrygen_attributes['description'] ?? '';
$ambrygen_items       = is_array( $ambrygen_attributes['items'] ?? null ) ? $ambrygen_attributes['items'] : array();
$ambrygen_has_heading = '' !== trim( wp_strip_all_tags( $ambrygen_heading ) );
$ambrygen_has_desc    = '' !== trim( wp_strip_all_tags( $ambrygen_description ) );
$ambrygen_heading_id  = wp_unique_id( 'symptoms-heading-' );

if ( $ambrygen_anchor ) {
	$ambrygen_heading_id = $ambrygen_anchor . '-heading';
} elseif ( $ambrygen_block_id ) {
	$ambrygen_heading_id = $ambrygen_block_id . '-heading';
}

$ambrygen_wrapper_args = array(
	'class' => 'symptoms',
);

if ( $ambrygen_anchor || $ambrygen_block_id ) {
	$ambrygen_wrapper_args['id'] = $ambrygen_anchor ?: $ambrygen_block_id;
}

if ( $ambrygen_has_heading ) {
	$ambrygen_wrapper_args['role']            = 'region';
	$ambrygen_wrapper_args['aria-labelledby'] = $ambrygen_heading_id;
} else {
	$ambrygen_wrapper_args['role']       = 'region';
	$ambrygen_wrapper_args['aria-label'] = __( 'Icon with split content', 'ambrygen-web' );
}

$ambrygen_wrapper_attributes = get_block_wrapper_attributes(
	$ambrygen_wrapper_args
);
?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="symptoms__grid">
		<div class="symptoms__left">
			<?php if ( $ambrygen_items ) : ?>
				<?php foreach ( $ambrygen_items as $ambrygen_item ) : ?>
					<?php
					$ambrygen_icon_id  = isset( $ambrygen_item['iconId'] ) ? absint( $ambrygen_item['iconId'] ) : 0;
					$ambrygen_icon_url = isset( $ambrygen_item['iconUrl'] ) ? esc_url_raw( $ambrygen_item['iconUrl'] ) : '';
					$ambrygen_icon_alt = isset( $ambrygen_item['iconAlt'] ) ? sanitize_text_field( $ambrygen_item['iconAlt'] ) : '';
					$ambrygen_text     = isset( $ambrygen_item['text'] ) ? sanitize_text_field( $ambrygen_item['text'] ) : '';
					?>
					<div class="symptoms__item">
						<?php if ( $ambrygen_icon_id || $ambrygen_icon_url ) : ?>
							<?php
							// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped -- Helper::image_from_source() escapes attributes and returns wp_kses_post()-sanitized image markup.
							echo Helper::image_from_source(
								$ambrygen_icon_id,
								$ambrygen_icon_url,
								'full',
								array(
									'class'   => 'symptoms__icon',
									'alt'     => $ambrygen_icon_alt,
									'loading' => 'lazy',
								)
							);
							// phpcs:enable WordPress.Security.EscapeOutput.OutputNotEscaped
							?>
						<?php endif; ?>

						<?php if ( $ambrygen_text ) : ?>
							<div class="symptoms__text">
								<?php echo esc_html( $ambrygen_text ); ?>
							</div>
						<?php endif; ?>
					</div>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>

		<div class="symptoms__right">
			<?php if ( $ambrygen_has_heading ) : ?>
				<<?php echo tag_escape( $ambrygen_heading_tag ); ?> id="<?php echo esc_attr( $ambrygen_heading_id ); ?>" class="heading-4 block-title mb-0 symptoms__title">
					<?php echo wp_kses( $ambrygen_heading, Helper::allowed_heading_html() ); ?>
				</<?php echo tag_escape( $ambrygen_heading_tag ); ?>>
			<?php endif; ?>

			<?php if ( $ambrygen_has_heading && $ambrygen_has_desc ) : ?>
				<div class="is-style-gl-s12" aria-hidden="true"></div>
			<?php endif; ?>

			<?php if ( $ambrygen_has_desc ) : ?>
				<div class="subtitle1-regular symptoms__desc">
					<?php echo wp_kses_post( $ambrygen_description ); ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>
