<?php
/**
 * Render: Split Content Section Block.
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

defined( 'ABSPATH' ) || exit;

use Ambrygen\Theme\Core\Helper;

$ambrygen_attributes           = is_array( $attributes ) ? $attributes : array();
$ambrygen_block_id             = isset( $ambrygen_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_attributes['blockId'] ) : '';
$ambrygen_title                = $ambrygen_attributes['title'] ?? '';
$ambrygen_title_tag            = Helper::get_heading_tag( $ambrygen_attributes['titleTag'] ?? 'h2', 'h2' );
$ambrygen_description          = $ambrygen_attributes['description'] ?? '';
$ambrygen_is_medium            = ! empty( $ambrygen_attributes['isMediumText'] );
$ambrygen_is_header_vertical   = ! empty( $ambrygen_attributes['isHeaderVertical'] );
$ambrygen_background_image_id  = isset( $ambrygen_attributes['backgroundImageId'] ) ? absint( $ambrygen_attributes['backgroundImageId'] ) : 0;
$ambrygen_background_image_url = isset( $ambrygen_attributes['backgroundImage'] ) ? (string) $ambrygen_attributes['backgroundImage'] : '';
$ambrygen_background_image_alt = isset( $ambrygen_attributes['backgroundImageAlt'] ) ? sanitize_text_field( $ambrygen_attributes['backgroundImageAlt'] ) : '';
$ambrygen_has_title            = '' !== trim( wp_strip_all_tags( $ambrygen_title ) );
$ambrygen_has_description      = '' !== trim( wp_strip_all_tags( $ambrygen_description ) );
$ambrygen_title_id             = $ambrygen_has_title ? wp_unique_id( 'split-content-section-title-' ) : '';

$ambrygen_wrapper_attributes_array = array(
	'class' => 'heading-content-section wp-block-ambrygen-split-content-section' . ( $ambrygen_is_medium ? ' variation-medium-text' : '' ),
	'role'  => 'region',
);

if ( $ambrygen_block_id ) {
	$ambrygen_wrapper_attributes_array['id'] = $ambrygen_block_id;
}

if ( $ambrygen_title_id ) {
	$ambrygen_wrapper_attributes_array['aria-labelledby'] = $ambrygen_title_id;
} else {
	$ambrygen_wrapper_attributes_array['aria-label'] = esc_attr__( 'Split content section', 'ambrygen-web' );
}

$ambrygen_wrapper_attributes = get_block_wrapper_attributes( $ambrygen_wrapper_attributes_array );

$ambrygen_richtext_allowed = array(
	'span' => array(
		'class' => true,
		'data-tooltip' => true,
		'data-tooltip-title' => true,
	),
	'div' => array(
		'class' => true,
	),
	'mark' => array(
		'class' => true,
		'style' => true,
	),
	'br' => array(),
	'strong' => array(),
	'em' => array(),
	'a' => array(
		'href' => true,
		'title' => true,
		'target' => true,
		'rel' => true,
		'class' => true,
	),
);
?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<?php if ( $ambrygen_background_image_id || $ambrygen_background_image_url ) : ?>
		<div class="block-bg-image">
			<?php
			// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Helper returns escaped image markup from a sanitized attachment ID or URL.
			echo Helper::image_from_source(
				$ambrygen_background_image_id,
				$ambrygen_background_image_url,
				'medium',
				array(
					'alt'      => $ambrygen_background_image_alt,
					'loading'  => 'lazy',
					'decoding' => 'async',
				)
			);
			?>
		</div>
	<?php endif; ?>
	<div class="heading-content-section__inner block__rowflex is-<?php echo esc_attr( $ambrygen_is_header_vertical ? 'vertical' : 'horizontal' ); ?>">
		<?php if ( $ambrygen_has_title ) : ?>
			<<?php echo tag_escape( $ambrygen_title_tag ); ?> id="<?php echo esc_attr( $ambrygen_title_id ); ?>" class="heading-content-section__title heading-3 block-title mb-0
				block__rowflex--heading-title js-gsap-fade">
				<?php
				echo wp_kses( $ambrygen_title, $ambrygen_richtext_allowed );
				?>
			</<?php echo tag_escape( $ambrygen_title_tag ); ?>>
		<?php endif; ?>

		<div class="heading-content-wrapper">
			<?php if ( $ambrygen_has_description ) : ?>
				<div
					class="heading-content-section__description block__rowflex--block-content block-description js-gsap-fade">
					<?php echo wp_kses( $ambrygen_description, $ambrygen_richtext_allowed ); ?>
				</div>

			<?php endif; ?>

			<?php if ( trim( $content ) ) : ?>
				<div class="is-style-gl-s24" aria-hidden="true"></div>
				<div class="heading-content-section__content js-gsap-fade">
					<?php echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>
