<?php
	/**
	 * Render: Steps Image Alongside Text Block
	 *
	 * @param array    $attributes The block attributes.
	 * @param string   $content    The block content.
	 * @param WP_Block $block      The block instance.
	 *
	 * @package ambrygen
	 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

	use Ambrygen\Theme\Core\Helper;

	$ambrygen_attributes         = is_array( $attributes ) ? $attributes : array();
	$ambrygen_block_id           = isset( $ambrygen_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_attributes['blockId'] ) : '';
	$ambrygen_heading            = isset( $ambrygen_attributes['heading'] ) ? $ambrygen_attributes['heading'] : '';
	$ambrygen_description        = isset( $ambrygen_attributes['description'] ) ? $ambrygen_attributes['description'] : '';
	$ambrygen_heading_tag        = Helper::get_heading_tag( $ambrygen_attributes['headingTag'] ?? 'h2', 'h2' );
	$ambrygen_show_full_image    = isset( $ambrygen_attributes['showFullImage'] ) ? (bool) $ambrygen_attributes['showFullImage'] : false;
	$ambrygen_has_heading        = '' !== trim( wp_strip_all_tags( $ambrygen_heading ) );
	$ambrygen_has_description    = '' !== trim( wp_strip_all_tags( $ambrygen_description ) );
	$ambrygen_heading_id         = $ambrygen_has_heading ? wp_unique_id( 'steps-image-alongside-text-heading-' ) : '';
	$ambrygen_has_header_content = $ambrygen_has_heading || $ambrygen_has_description;

	$ambrygen_wrapper_classes = array( 'steps-iot-block block-layout' );
if ( $ambrygen_show_full_image ) {
	$ambrygen_wrapper_classes[] = 'show-full-image';
}

	$ambrygen_wrapper_args = array(
		'class' => implode( ' ', $ambrygen_wrapper_classes ),
	);

	if ( $ambrygen_block_id ) {
		$ambrygen_wrapper_args['id'] = $ambrygen_block_id;
	}

	if ( $ambrygen_heading_id ) {
		$ambrygen_wrapper_args['aria-labelledby'] = $ambrygen_heading_id;
	} else {
		$ambrygen_wrapper_args['aria-label'] = __( 'Steps image alongside text', 'ambrygen-web' );
	}

	$ambrygen_wrapper_attributes = get_block_wrapper_attributes(
		$ambrygen_wrapper_args
	);
	?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>

	<div class="steps-iot-block__header block__rowflex">

		<?php if ( $ambrygen_has_heading ) : ?>
			<div class="block__rowflex--col-left">
			<<?php echo tag_escape( $ambrygen_heading_tag ); ?>
				id="<?php echo esc_attr( $ambrygen_heading_id ); ?>"
				class="heading-3 block-title mb-0 block__rowflex--heading-title js-gsap-fade">
				<?php echo wp_kses( $ambrygen_heading, Helper::allowed_heading_html() ); ?>
			</<?php echo tag_escape( $ambrygen_heading_tag ); ?>>
			</div>
		<?php endif; ?>

		<?php if ( $ambrygen_has_description ) : ?>
			<div class="block__rowflex--block-content subtitle-1-regular js-gsap-fade">
				<?php echo wp_kses_post( $ambrygen_description ); ?>
			</div>
		<?php endif; ?>

	</div>

	<?php if ( $ambrygen_has_header_content ) : ?>
		<div class="is-style-gl-s50" aria-hidden="true"></div>
	<?php endif; ?>

	<div class="vertical-tabs js-gsap-fade" role="tablist" aria-orientation="vertical">
		<?php echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- InnerBlocks content is escaped by WordPress core. ?>
	</div>

	</div>
