<?php
/**
 * Render: Gallery Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Ambrygen\Theme\Core\Helper;

$ambrygen_heading             = $attributes['heading'] ?? '';
$ambrygen_description         = $attributes['description'] ?? '';
$ambrygen_heading_tag_default = isset( $block->block_type->attributes['headingTag']['default'] ) ? $block->block_type->attributes['headingTag']['default'] : 'h2';
$ambrygen_heading_tag         = $attributes['headingTag'] ?? $ambrygen_heading_tag_default;
$ambrygen_variation           = $attributes['variation'] ?? '';
$ambrygen_top_image_id        = isset( $attributes['topImageID'] ) ? (int) $attributes['topImageID'] : 0;
$ambrygen_top_image_url       = $attributes['topImageURL'] ?? '';
$ambrygen_top_image_alt       = $attributes['topImageAlt'] ?? '';
$ambrygen_grid_columns        = $attributes['gridColumns'] ?? '2';
$tab_block_id                 = $attributes['blockId'] ?? '';

/**
 * Auto-adjust grid columns based on number of items
 */
$inner_blocks          = $block->inner_blocks ?? array();
$item_count            = count( $inner_blocks );
$grid_map              = array(
	1 => '1',
	2 => '2',
	3 => '3',
	4 => '4',
);
$ambrygen_grid_columns = $grid_map[ $item_count ] ?? '3';

/**
 * Set context for inner blocks
 */
$block->context['ambrygen/galleryGridColumns'] = $ambrygen_grid_columns;

/**
 * WCAG: Prevent empty content containers
 */
if ( empty( trim( $content ) ) ) {
	return;
}

$ambrygen_heading_tag = Helper::get_heading_tag( $ambrygen_heading_tag, $ambrygen_heading_tag_default );
$tab_block_id         = $attributes['blockId'] ?? '';
/**
 * WCAG: Prevent empty headings being announced
 */
if ( empty( trim( wp_strip_all_tags( $ambrygen_heading ) ) ) ) {
	$ambrygen_heading = '';
}

/**
 * WCAG 2.1 AA: Accessible block labeling (2.4.6)
 */
$block_id = 'image-grid-' . wp_unique_id();

/**
 * Block wrapper attributes (no HTML change)
 */


$amb_class = '';
if ( 'variation-features' === $ambrygen_variation || 'image-content-grid' === $ambrygen_variation ) {
	$amb_class = 'variation-team';
} else {
	$amb_class = '';
}



$ambrygen_wrapper_attrs = array(
	'class'           => 'image-grid-block  block-' . sanitize_html_class( $ambrygen_variation ) . ' ' . $amb_class . ' grid-column' . $ambrygen_grid_columns,
	'aria-labelledby' => $ambrygen_heading ? esc_attr( $block_id ) : '',
	'id'              => $tab_block_id,
);

if ( $ambrygen_heading ) {
	$ambrygen_wrapper_attrs['aria-labelledby'] = $block_id;
}

$ambrygen_wrapper_attributes = get_block_wrapper_attributes( $ambrygen_wrapper_attrs );
?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>
	<div class="get-started-block">

		<?php if ( 'image-content-grid' === $ambrygen_variation ) : ?>

		<div class="our-approach__header logo-title-section">
			<?php if ( $ambrygen_top_image_id || $ambrygen_top_image_url ) : ?>

					<div class="logo-title-section__icon js-gsap-fade">
					<?php
					// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped -- Helper::image_from_source() escapes attributes and returns wp_kses_post()-sanitized image markup.
					echo Helper::image_from_source(
						$ambrygen_top_image_id,
						$ambrygen_top_image_url,
						'large',
						array(
							'class'   => 'logo-title-section__logo',
							'loading' => 'lazy',
							'alt'     => $ambrygen_heading
											? esc_attr( wp_strip_all_tags( $ambrygen_heading ) )
											: '',
						)
					);
					// phpcs:enable WordPress.Security.EscapeOutput.OutputNotEscaped
					?>
					</div>
					<div class="is-style-gl-s50" aria-hidden="true"></div>

				<?php endif; ?>
				<div class="logo-title-section__content">
					<?php if ( $ambrygen_heading ) : ?>
						<<?php echo tag_escape( $ambrygen_heading_tag ); ?>
							class="heading-2 block-title mb-0 js-gsap-fade"
							id="<?php echo esc_attr( $block_id ); ?>">
							<?php
							echo wp_kses(
								$ambrygen_heading,
								Helper::allowed_heading_html()
							);
							?>
						</<?php echo tag_escape( $ambrygen_heading_tag ); ?>>
					<?php endif; ?>

					<?php if ( $ambrygen_description ) : ?>
						<div class="is-style-gl-s16" aria-hidden="true"></div>
						<div class="body1-reg logo-title-section__description js-gsap-fade">
							<?php echo wp_kses_post( $ambrygen_description ); ?>
						</div>
					<?php endif; ?>
				</div>
			</div>

		<?php elseif ( 'variation-features' === $ambrygen_variation ) : ?>
			<div class="our-approach__header block__rowflex">
				<?php if ( $ambrygen_heading ) : ?>
					<<?php echo tag_escape( $ambrygen_heading_tag ); ?>
						class="heading-content-section__title heading-3 block-title mb-0
						block__rowflex--heading-title js-gsap-fade"
						id="<?php echo esc_attr( $block_id ); ?>">
						<?php
						echo wp_kses(
							$ambrygen_heading,
							Helper::allowed_heading_html()
						);
						?>
					</<?php echo tag_escape( $ambrygen_heading_tag ); ?>>
				<?php endif; ?>

				<?php if ( $ambrygen_description ) : ?>
					<div class="heading-content-wrapper">
						<div class="block__rowflex--block-content subtitle1-reg js-gsap-fade">
							<?php echo wp_kses_post( $ambrygen_description ); ?>
						</div>
					</div>
				<?php endif; ?>

			</div>



		<?php elseif ( $ambrygen_heading ) : ?>

			<<?php echo tag_escape( $ambrygen_heading_tag ); ?>
				class="block-title heading-3 mb-0 js-gsap-fade"
				id="<?php echo esc_attr( $block_id ); ?>">
				<?php
				echo wp_kses(
					$ambrygen_heading,
					Helper::allowed_heading_html()
				);
				?>
			</<?php echo tag_escape( $ambrygen_heading_tag ); ?>>

		<?php endif; ?>

		<div class="card-grid-block" role="list">
			<?php echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Content is pre-escaped by WordPress core. ?>
		</div>

	</div>
</div>
