<?php
/**
 * Render: Theme Form Block
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The block content.
 * @param WP_Block $block      The block instance.
 *
 * @package ambrygen
 */

defined( 'ABSPATH' ) || exit;

use Ambrygen\Theme\Core\Helper;

// Prefix all variables with theme/plugin name.
$ambrygen_theme_form_attributes      = $attributes ?? array();
$ambrygen_theme_form_content         = $content ?? '';
$ambrygen_theme_form_has_form_output = '' !== trim( wp_strip_all_tags( $ambrygen_theme_form_content ) );

$ambrygen_theme_form_block_id      = isset( $ambrygen_theme_form_attributes['blockId'] ) ? sanitize_html_class( $ambrygen_theme_form_attributes['blockId'] ) : '';
$ambrygen_theme_form_title         = $ambrygen_theme_form_attributes['title'] ?? '';
$ambrygen_theme_form_content_text  = $ambrygen_theme_form_attributes['content'] ?? '';
$ambrygen_theme_form_heading_level = Helper::get_heading_tag( $ambrygen_theme_form_attributes['headingTag'] ?? 'h2', 'h2' );

$ambrygen_theme_form_heading_id = wp_unique_id( 'theme-form-heading-' );
$ambrygen_wrapper_attributes    = get_block_wrapper_attributes(
	$ambrygen_theme_form_block_id
		? array(
			'class' => 'theme-form-block',
			'id'    => $ambrygen_theme_form_block_id,
		)
		: array( 'class' => 'theme-form-block' )
);
?>

<div <?php echo $ambrygen_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes(). ?>>

	<div class="heading-center center-align">
		<?php if ( $ambrygen_theme_form_title ) : ?>
			<<?php echo tag_escape( $ambrygen_theme_form_heading_level ); ?> id="<?php echo esc_attr( $ambrygen_theme_form_heading_id ); ?>" class="heading-3 block-title mb-0 js-gsap-fade">
				<?php echo wp_kses( $ambrygen_theme_form_title, Helper::allowed_heading_html() ); ?>
			</<?php echo tag_escape( $ambrygen_theme_form_heading_level ); ?>>
		<?php endif; ?>

		<?php if ( $ambrygen_theme_form_content_text ) : ?>
			<div class="is-style-gl-s24" aria-hidden="true"></div>
			<div class="heading-content text-md-regular js-gsap-fade">
				<?php echo wp_kses_post( $ambrygen_theme_form_content_text ); ?>
			</div>
		<?php endif; ?>
	</div>

	<?php if ( $ambrygen_theme_form_has_form_output ) : ?>
		<section class="theme-form-block__form js-gsap-fade"
			<?php if ( $ambrygen_theme_form_title ) : ?>
				aria-labelledby="<?php echo esc_attr( $ambrygen_theme_form_heading_id ); ?>"
			<?php else : ?>
				aria-label="<?php echo esc_attr__( 'Contact form', 'ambrygen-web' ); ?>"
			<?php endif; ?>
		>
			<?php echo $ambrygen_theme_form_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- InnerBlocks content is rendered by WordPress. ?>
		</section>
	<?php endif; ?>

</div>
